version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: "no"
    networks: 
      - companycob
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=companycob
      - POSTGRES_USER=companycob
      - POSTGRES_DB=companycob

#####
# check opened connections:
#####
# lsof -nP -i :5432 -sTCP:ESTABLISHED
#

  localstack:
    build:
      context: ./localstack
    container_name: localstack
    restart: "no"
    networks:
      - companycob
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - LOCALSTACK_SERVICES=s3,sqs

networks: 
  companycob: