version: '3.8'

services:
  localstack:
    build:
      context: .
    container_name: localstack
    restart: "no"
    networks:
      - companycob
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - LOCALSTACK_SERVICES=s3,sqs

networks:
  companycob:
