version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: "no"
    networks: 
      - companycob
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=companycob
      - POSTGRES_USER=companycob
      - POSTGRES_DB=companycob

networks: 
  companycob: 

#####
# check opened connections:
#####
# lsof -nP -i :5432 -sTCP:ESTABLISHED
#