version: '3.8'
services:
  keycloak:
    build:
      context: .
    container_name: keycloak
    networks:
      - companycob
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-companycob-export.json

networks:
  companycob: