name: Build

on: [push, pull_request]

jobs:
  build-registration-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./registration-api

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      run: ./gradlew build -x test -x check
    - name: Test
      run: ./gradlew test check